name: Deploy

on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v1
        with:
          node-version: 20

      - run: npm add -D vitepress

      - run: npm run docs:build

      - name: deploy to netlify (prod)
        if: ${{ github.ref_name == 'main' }}
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=.vitepress/dist --prod

      - name: deploy to netlify (dev)
        if: ${{ github.ref_name != 'main' }}
        id: deploy-neflify-dev
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=.vitepress/dist --deployId=preview-${{ github.event.number }}

      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'This pull request is being automatically deployed to Netlify.\n\n🔍 Inspect: ${{ steps.deploy-neflify-dev.outputs.NETLIFY_LOGS_URL }}\n✅ Preview: ${{ steps.deploy-neflify-dev.outputs.NETLIFY_URL }}'
            })
